name: Deploy Staging

on:
  push:
    branches: [ 'staging' ]

permissions:
  contents: read

concurrency:
  group: deploy-staging
  cancel-in-progress: true

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
